In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [2]:
df = pd.DataFrame({
    'Age': [18, 22, 25, 30, 35, 60],
    'Income': [1000, 1500, 2000, 3000, 5000, 20000]  # є аутлайер
})

df

   Age  Income
0   18    1000
1   22    1500
2   25    2000
3   30    3000
4   35    5000
5   60   20000

In [3]:
scaler = StandardScaler()

df_scaled = df.copy()
df_scaled[['Age', 'Income']] = scaler.fit_transform(df[['Age', 'Income']])

df_scaled

        Age    Income
0 -0.990905 -0.664319
1 -0.700884 -0.589113
2 -0.483368 -0.513907
3 -0.120842 -0.363495
4  0.241684 -0.062672
5  2.054315  2.193506

In [4]:
scaler = MinMaxScaler()

df_scaled = df.copy()
df_scaled[['Age', 'Income']] = scaler.fit_transform(df[['Age', 'Income']])

df_scaled

        Age    Income
0  0.000000  0.000000
1  0.095238  0.026316
2  0.166667  0.052632
3  0.285714  0.105263
4  0.404762  0.210526
5  1.000000  1.000000

In [5]:
scaler = RobustScaler()

df_scaled = df.copy()
df_scaled[['Age', 'Income']] = scaler.fit_transform(df[['Age', 'Income']])

df_scaled

        Age    Income
0 -0.863636 -0.521739
1 -0.500000 -0.347826
2 -0.227273 -0.173913
3  0.227273  0.173913
4  0.681818  0.869565
5  2.954545  6.086957

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])